# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 05:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookedTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_tickets', models.IntegerField(default=1)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_name', models.CharField(max_length=100)),
                ('total_tickets', models.IntegerField(default=100)),
                ('ticket_price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_trains', to='railways.City')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_trains', to='railways.City')),
            ],
        ),
        migrations.AddField(
            model_name='bookedticket',
            name='train',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='railways.Train'),
        ),
    ]
